### ISSUE TITLE
Use composer to automatically generate translations and suggestions for migrating namespaces

### ISSUE THREAD

**Issue by xutl** [yiisoft/yii2-composer#17]
We can extend the composer's configuration
```json
{
    "type": "yii2-extension",
    ...,
    "extra": {
        "yii": {
            "name": "admin",
            "i18n": {
                "class":"yii\\i18n\\PhpMessageSource",
                "basePath":"@abc/admin/message"
            },
            "migrationNamespace": "abc\\admin\\migrations"
        }
    }
}
```
Then `composer install` will automatically generate `vendor/yiisoft/i18n.php`, `vendor/yiisoft/ migrations.php`

view `vendor/yiisoft/i18n.php`:
```php
return array (
  'admin' => 
  array (
    'class' => 'yii\\i18n\\PhpMessageSource',
    'basePath' => '@abc/admin/message',
  ),
 ...,
);
```

view `vendor/yiisoft/ migrations.php`:

```php

return array (
  0 => 'abc\\admin\\migrations',
);
```

In the application development, only the user manually merge the two arrays to the application configuration can be easily used.
This can be avoided in large systems or modules in more systems, due to forget or lack of configuration caused by low-level errors.

I implemented this feature in a multi-module system and automatically generated the minimum configuration for the foreground background.
Related code in https://github.com/yuncms/yii2-composer

If the review is feasible, I will create a pull.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by SilverFire** [comment]
The problem is called "autoconfiguration" and it is not limited to translations.
My colleague @hiqsol created https://github.com/hiqdev/composer-config-plugin to solve this problem, and we use it in our applications as a standard way to load configuration from modules, but this plugin is not widely used in Yii infrastructure.

**Comment by SilverFire** [comment]
I think we had similar issue in main yii2 repo, but I can not find it. @samdark do you remember it?

**Comment by xutl** [comment]
Use examples at https://github.com/yuncms/yuncms-app-advanced/blob/master/console/config/main.php#L10

If you want to try the whole program build `composer create-project yuncms/yuncms-app-advanced:dev-master --keep-vcs`

**Comment by xutl** [comment]
@SilverFire I think dealing with translation and migration is more in line with the needs of most people.

**Comment by cebe** [comment]
Can't all of this be solved by using the existing extension bootstrapping mechanism?

**Comment by xutl** [comment]
@cebe For restful or multi-module applications, if each time to load bootstrap one is affecting performance, the other is really inconvenient, some applications do not have to bootstrap, but optional i18n and migration is a good choice

**Comment by xutl** [comment]
@cebe If you use the B module, where the B module references the A module model, this time if you do not directly access the A application, in the Module module's `Module :: init` method even if you write the code for the auto-registration language configuration, Role, my idea just to solve a similar problem.

**Comment by klimov-paul** [comment]
For me this isssue is out of the Yii scope; there are too many posibilities, possible project structures and configurations.
For example: particular project may have several separated migration commands to support several databases or for other purposes. Someone may need to have migrations for MongoDB instead of relational DB and so on.
If you wish your project to pick up or compose some configuration from installed modules you should manage it on your own creating your own composer package, which may extend `yii2-composer` if you like.

**Comment by hiqsol** [comment]
I've written an article describing this question and a bit more how I see the problem on the whole.

[english version](https://hiqdev.com/pages/articles/app-organization)
[russian version](https://habrahabr.ru/post/329286/)

I agree with @klimov-paul  that it should put out of Yii scope. But I think the community should discuss and select some method for plugin autoconfiguration.

**Comment by xutl** [comment]
I agree with @hiqsol

**Comment by klimov-paul** [comment]
I do not like the idea of transforming Yii into WordPress, allowing particular extension to adjust the developer-defined configuration.
There is a sugnificant difference between PHP Framework (which Yii is) and CMS (which WordPress is).
Autoconfiguration of the modules is an internal taks of CMS - not the framework's one.
Also I do not understand, why conding inside `composer.json` is better then ar regualr `*.php` file.

>  I think the community should discuss and select some method for plugin autoconfiguration.

`yii2-composer` already provides ability of running shell scripts after installation - this is more or less universal task, while creating file structure or manipulation of the configuration (while configuration files location is undetermined) is too specific.
I do not consider this discussion to be a bug report, while such feature can not be accepted at the core package. Thus I suggest such disscussion should take place at forum instead of GitHub.

**Comment by hiqsol** [comment]
Sorry @klimov-paul  I'm afraid you underestimate the issue.
Symfony is known to be framework and not a CMS and still they are pretty serious about the question, please see Symfony Flex:
https://symfony.com/doc/current/setup/flex.html

But of course it's not a bug :) And has to be discussed elsewhere.

**Comment by rob006** [comment]
I think we need some "blessed" way to define config adjustments required/proposed by extensions. Personally I would definitely not want an automagic that changes configuration of my app behind my back, but I also don't want to manually track required changes on each update. I think that generating single file with array of config adjustments required by each of extensions would be enough. It could be tracked by VCS, so you can easily detect required changes ofter updating dependencies. And if you want you can merge proposed config directly with `ArrayHelper::merge()`. This will make updating/configuring much easier, but it will not automatically do it for you.
